Repository diskord-dev/diskord, pull requests merged in 2021-11, with the labels that each got.

#20 Application commands revisit
  diskord/application/command.py
  diskord/application/mixins.py
  diskord/application/slash.py
  diskord/application_commands.py
  diskord/client.py
  diskord/ext/commands/cog.py
  diskord/types/guild.py
  docs/application_commands.rst
  examples/application_commands/autocomplete.py
  examples/application_commands/autocomplete_multiple_options.py
Labels: breaking change, application commands

#28 Support for guild events.
  diskord/__init__.py
  diskord/enums.py
  diskord/events.py
  diskord/flags.py
  diskord/guild.py
  diskord/http.py
  diskord/state.py
  diskord/types/events.py
  docs/api.rst
Labels: feature request, s: todo

#30 Implement thread starter message
  diskord/threads.py
Labels: feature request, changes requested
